### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by miika** [digiaonline/paytrail-php#3]
PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).

**Comment by Jalle19** [comment]
Might as well get rid of the Common namespace since we kinda have to bump the major versiob anyway if we rename the basest of base classes. Everything in Common could be moved to other existing namespaces.

**Comment by Jalle19** [comment]
Fixed by #4
